server:
  port: 80

spring:
  cloud:
    consul:
      enabled: true
      host: ${SIMPLE_MUSIC_REGISTRY_HOST}
      port: ${SIMPLE_MUSIC_REGISTRY_HOST}
      discovery:
        instanceId: ${spring.application.name}:${random.value}

security:
  service-id: avatars
  service-password: secret
  token-lifetime: 30
