server:
  port: 80

content:
  default-avatar-path: /var/www/img/default.jpg

spring:
  cloud:
    consul:
      enabled: true
      host: ${SIMPLE_MUSIC_REGISTRY_HOST}
      port: ${SIMPLE_MUSIC_REGISTRY_PORT}
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 10s
        health-check-timeout: 20s
        health-check-critical-timeout: 20s

security:
  service-id: avatars
  service-password: secret
  token-lifetime: 30
