server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:service.jks
    key-store-password: secret
    key-alias: service

spring:
  cloud:
    consul:
      enabled: true
      discovery:
        instanceId: ${spring.application.name}:${random.value}
